In [1]:
import pandas as pd
import numpy as np

In [105]:
exam_data = {
    'name':['Nikhil','Vishal','Divya','James','ankur','Vivek','Aman','Rahu','Lalit','lakshay'],
    'score':[12.9,9,16.5,np.nan,9,20,14.5,np.nan,8,19],
    'attempts':[1,3,2,3,2,3,1,1,2,1],
    'qualify':['yes','yes','yes','no','no','yes','yes','no','no','yes'],
}
labels=['a','b','c','d','e','f','g','h','i','j']

In [106]:
df=pd.DataFrame(exam_data, index=labels)

In [29]:
df

      name  score  attemps qualify
a   Nikhil   12.9        1     yes
b   Vishal    9.0        3      no
c    Divya   16.5        2     yes
d    James    NaN        3      no
e    ankur    9.0        2      no
f    Vivek   20.0        3     yes
g     Aman   14.5        1     yes
h     Rahu    NaN        1      no
i    Lalit    8.0        2      no
j  lakshay   19.0        1     yes

In [17]:
df[['name','score']]

      name  score
a   Nikhil   12.9
b   Vishal    9.0
c    Divya   16.5
d    James    NaN
e    ankur    9.0
f    Vivek   20.0
g     Aman   14.5
h     Rahu    NaN
i    Lalit    8.0
j  lakshay   19.0

## iloc only take integers and arguments

In [76]:
data = df.iloc[[1,3,5,6],[0,1]]

In [77]:
data

     name  score
b  Vishal    9.0
d   James    NaN
f   Vivek   20.0
g    Aman   14.5

In [60]:
filtered_data = df[df['attempts']>2]
filtered_data

     name  score  attempts qualify
b  Vishal    9.0         3      no
d   James    NaN         3      no
f   Vivek   20.0         3     yes

In [54]:
filtered_data = df.loc[(df['attempts']>2)&(df['qualify']=='yes')]

In [55]:
filtered_data

    name  score  attempts qualify
f  Vivek   20.0         3     yes

In [66]:
df

      name  score  attempts qualify
a   Nikhil   12.9         1     yes
b   Vishal    9.0         3     yes
c    Divya   16.5         2     yes
d    James    NaN         3      no
e    ankur    9.0         2      no
f    Vivek   20.0         3     yes
g     Aman   14.5         1     yes
h     Rahu    NaN         1      no
i    Lalit    8.0         2      no
j  lakshay   19.0         1     yes

In [67]:
fdata = df.query("attempts > 2 & qualify == 'yes'")
fdata

     name  score  attempts qualify
b  Vishal    9.0         3     yes
f   Vivek   20.0         3     yes

In [68]:
no_of_rows = len(df.axes[0])
no_of_columns = len(df.axes[1])

In [75]:
print(no_of_rows)

10

In [73]:
print(no_of_columns)

4

In [78]:
fdata = df.query("attempts < 2 & score > 15")

In [79]:
fdata

      name  score  attempts qualify
j  lakshay   19.0         1     yes

In [85]:
fdata = df.loc[(df['attempts']<2)&(df['score']>15)]

In [86]:
fdata

      name  score  attempts qualify
j  lakshay   19.0         1     yes

In [93]:
df.loc['d','score']=11.5

In [94]:
df

      name  score  attempts qualify
a   Nikhil   12.9         1     yes
b   Vishal    9.0         3     yes
c    Divya   16.5         2     yes
d    James   11.5         3      no
e    ankur    9.0         2      no
f    Vivek   20.0         3     yes
g     Aman   14.5         1     yes
h     Rahu    NaN         1      no
i    Lalit    8.0         2      no
j  lakshay   19.0         1     yes

## write a pandas program to replace the 'qualify' column contains the values 'yes' and 'no' with True and false

In [107]:
df['qualify']=df['qualify'].map({'yes':True,'no':False})

In [108]:
df

      name  score  attempts  qualify
a   Nikhil   12.9         1     True
b   Vishal    9.0         3     True
c    Divya   16.5         2     True
d    James    NaN         3    False
e    ankur    9.0         2    False
f    Vivek   20.0         3     True
g     Aman   14.5         1     True
h     Rahu    NaN         1    False
i    Lalit    8.0         2    False
j  lakshay   19.0         1     True

In [114]:
df['remark']=df['qualify'].map({True:'Congratulation',False:'Study Hard MF'})

In [115]:
df

      name  score  attempts  qualify          remark
a   Nikhil   12.9         1     True  Congratulation
b   Vishal    9.0         3     True  Congratulation
c    Divya   16.5         2     True  Congratulation
d    James    NaN         3    False   Study Hard MF
e    ankur    9.0         2    False   Study Hard MF
f    Vivek   20.0         3     True  Congratulation
g     Aman   14.5         1     True  Congratulation
h     Rahu    NaN         1    False   Study Hard MF
i    Lalit    8.0         2    False   Study Hard MF
j  lakshay   19.0         1     True  Congratulation

In [116]:
df[df['name']=='Lalit']='harry'

C:\Users\visha\AppData\Local\Temp\ipykernel_2704\1500975149.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'harry' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df[df['name']=='Lalit']='harry'
C:\Users\visha\AppData\Local\Temp\ipykernel_2704\1500975149.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'harry' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df[df['name']=='Lalit']='harry'
C:\Users\visha\AppData\Local\Temp\ipykernel_2704\1500975149.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'harry' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df[df['name']=='Lalit']='harry'