In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [6]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [7]:
data = ['Ram','Shreya','Mohan','sohan']
df = pd.DataFrame(data)
df

        0
0     Ram
1  Shreya
2   Mohan
3   sohan

In [8]:
## making dataFrame from list of list

In [9]:
data = [['Ram',23,89000],['Shyam',22,23000],['Mohan',25,58000],['Vishal',24,70000]]
df=pd.DataFrame(data)

In [10]:
df

        0   1      2
0     Ram  23  89000
1   Shyam  22  23000
2   Mohan  25  58000
3  Vishal  24  70000

In [11]:
df[1]

0    23
1    22
2    25
3    24
Name: 1, dtype: int64

In [12]:
df=df.rename(columns={0:'Name',1:'Age',2:'Salary'})

In [13]:
df['Name']

0       Ram
1     Shyam
2     Mohan
3    Vishal
Name: Name, dtype: object

In [14]:
df['Salary'][0]

np.int64(89000)

In [15]:
## To print the content of row

In [16]:
df.loc[[0,1]]

    Name  Age  Salary
0    Ram   23   89000
1  Shyam   22   23000

In [17]:
df.iloc[0]

Name        Ram
Age          23
Salary    89000
Name: 0, dtype: object

In [38]:
df.loc[0:3,['first_name','last_name']]

  first_name   last_name
0  Margarete     Collopy
1      Shari  Charleston
2      Quinn    Loffhead
3     Idelle      Sleath

In [19]:
df[['Name','Salary']]

     Name  Salary
0     Ram   89000
1   Shyam   23000
2   Mohan   58000
3  Vishal   70000

In [20]:
## making dataframe using Dictionary

In [21]:
data = {'name':['Ram','Mohan','Sohan'],
        'age':[21,'',''],
        'marks':[89,90,91]
       }
df= pd.DataFrame(data)

In [22]:
df

    name age  marks
0    Ram  21     89
1  Mohan         90
2  Sohan         91

In [23]:
## making data Frame from list of Dictionary

In [24]:
data = [
        {
            'name':'Ram',
            'age':24,
            'marks':58000
        },
        {
            'name':'vishal',
            'age':21,
            'marks':59000
        },
        {
            'name':'Shaym',
            'age':24,
            'marks':57000
        },
        {
            'Gender':'male',
            'name':'Lalit'
        }        
]

df= pd.DataFrame(data)
df

     name   age    marks Gender
0     Ram  24.0  58000.0    NaN
1  vishal  21.0  59000.0    NaN
2   Shaym  24.0  57000.0    NaN
3   Lalit   NaN      NaN   male

In [25]:
df= pd.read_csv("sample.csv")
df

,id,first_name,last_name,email,gender,ip_address
0,1,Margarete,Collopy,mcollopy0@skyrock.com,Polygender,56.20.83.133
1,2,Shari,Charleston,scharleston1@ibm.com,Female,48.171.17.34
2,3,Quinn,Loffhead,qloffhead2@mapy.cz,Male,128.211.218.161
3,4,Idelle,Sleath,isleath3@unc.edu,Female,200.151.79.91
4,5,Barbara,Wolffers,bwolffers4@hugedomains.com,Female,148.212.173.251
...,...,...,...,...,...,...
95,96,Marrissa,Breens,mbreens2n@smh.com.au,Female,188.240.159.35
96,97,Mikey,Burkinshaw,mburkinshaw2o@shutterfly.com,Male,107.152.194.19
97,98,Eva,Guerrieri,eguerrieri2p@google.co.uk,Female,238.78.171.255
98,99,Kalie,Fennelly,kfennelly2q@netscape.com,Female,40.26.72.41
99,100,Jayme,Danielis,jdanielis2r@time.com,Male,64.64.138.178

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          100 non-null    int64
 1   first_name  100 non-null    object
 2   last_name   100 non-null    object
 3   email       100 non-null    object
 4   gender      100 non-null    object
 5   ip_address  100 non-null    object
dtypes: int64(1), object(5)
memory usage: 4.8+ KB

In [27]:
df.columns

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'ip_address'], dtype='object')

In [28]:
df.head()

,id,first_name,last_name,email,gender,ip_address
0,1,Margarete,Collopy,mcollopy0@skyrock.com,Polygender,56.20.83.133
1,2,Shari,Charleston,scharleston1@ibm.com,Female,48.171.17.34
2,3,Quinn,Loffhead,qloffhead2@mapy.cz,Male,128.211.218.161
3,4,Idelle,Sleath,isleath3@unc.edu,Female,200.151.79.91
4,5,Barbara,Wolffers,bwolffers4@hugedomains.com,Female,148.212.173.251

In [29]:
df.head(10)

,id,first_name,last_name,email,gender,ip_address
0,1,Margarete,Collopy,mcollopy0@skyrock.com,Polygender,56.20.83.133
1,2,Shari,Charleston,scharleston1@ibm.com,Female,48.171.17.34
2,3,Quinn,Loffhead,qloffhead2@mapy.cz,Male,128.211.218.161
3,4,Idelle,Sleath,isleath3@unc.edu,Female,200.151.79.91
4,5,Barbara,Wolffers,bwolffers4@hugedomains.com,Female,148.212.173.251
5,6,Patty,Locksley,plocksley5@google.ca,Male,45.218.46.58
6,7,Broddy,Browning,bbrowning6@squarespace.com,Male,1.253.141.119
7,8,Dianna,North,dnorth7@hp.com,Female,62.243.50.204
8,9,Erica,Epinoy,eepinoy8@yahoo.co.jp,Female,26.162.66.187
9,10,Winnifred,Rodge,wrodge9@forbes.com,Female,104.237.90.3

In [30]:
df.tail()

,id,first_name,last_name,email,gender,ip_address
95,96,Marrissa,Breens,mbreens2n@smh.com.au,Female,188.240.159.35
96,97,Mikey,Burkinshaw,mburkinshaw2o@shutterfly.com,Male,107.152.194.19
97,98,Eva,Guerrieri,eguerrieri2p@google.co.uk,Female,238.78.171.255
98,99,Kalie,Fennelly,kfennelly2q@netscape.com,Female,40.26.72.41
99,100,Jayme,Danielis,jdanielis2r@time.com,Male,64.64.138.178

In [31]:
df= pd.read_csv("sample.csv",usecols=['first_name','last_name'])

In [32]:
df

   first_name   last_name
0   Margarete     Collopy
1       Shari  Charleston
2       Quinn    Loffhead
3      Idelle      Sleath
4     Barbara    Wolffers
..        ...         ...
95   Marrissa      Breens
96      Mikey  Burkinshaw
97        Eva   Guerrieri
98      Kalie    Fennelly
99      Jayme    Danielis

[100 rows x 2 columns]

In [33]:
df= pd.read_csv("sample.csv",nrows=6)

In [34]:
df

,id,first_name,last_name,email,gender,ip_address
0,1,Margarete,Collopy,mcollopy0@skyrock.com,Polygender,56.20.83.133
1,2,Shari,Charleston,scharleston1@ibm.com,Female,48.171.17.34
2,3,Quinn,Loffhead,qloffhead2@mapy.cz,Male,128.211.218.161
3,4,Idelle,Sleath,isleath3@unc.edu,Female,200.151.79.91
4,5,Barbara,Wolffers,bwolffers4@hugedomains.com,Female,148.212.173.251
5,6,Patty,Locksley,plocksley5@google.ca,Male,45.218.46.58

In [47]:
data = pd.read_excel("sample.xlsx")
data

     id first_name last_name                    email  gender       ip_address
0     1      Nadia    Smylie     nsmylie0@tinyurl.com  Female    14.132.133.60
1     2    Frances  Skeleton    fskeleton1@paypal.com  Female  192.213.128.195
2     3     Margie  Flintoft     mflintoft2@baidu.com  Female      76.74.88.44
3     4  Betteanne  MacCombe     bmaccombe3@globo.com  Female    253.8.169.154
4     5   Nikolaos      Lees      nlees4@e-recht24.de    Male    89.223.221.90
..  ...        ...       ...                      ...     ...              ...
95   96    Ardenia   Downing     adowning2n@ifeng.com  Female    80.137.193.50
96   97       Olin     Cruce  ocruce2o@shareasale.com    Male   120.66.220.176
97   98     Paulie  Llewelyn     pllewelyn2p@furl.net    Male  116.116.155.238
98   99     Nickey      Corp      ncorp2q@twitter.com    Male   177.253.66.232
99  100       Brig      Orto        borto2r@intel.com    Male    174.90.251.17

[100 rows x 6 columns]

## Loading data from APIs

In [ ]:
import requests

In [ ]:
data=requests.get("https://jsonplaceholder.typicode.com/comments")
fdata=data.json()
df = pd.DataFrame(fdata)
df

In [48]:
data.loc[0:3,['first_name','last_name']]

  first_name last_name
0      Nadia    Smylie
1    Frances  Skeleton
2     Margie  Flintoft
3  Betteanne  MacCombe

In [49]:
data.loc[:,['first_name','last_name']]

   first_name last_name
0       Nadia    Smylie
1     Frances  Skeleton
2      Margie  Flintoft
3   Betteanne  MacCombe
4    Nikolaos      Lees
..        ...       ...
95    Ardenia   Downing
96       Olin     Cruce
97     Paulie  Llewelyn
98     Nickey      Corp
99       Brig      Orto

[100 rows x 2 columns]

In [53]:
data.set_index('first_name',inplace=True)

In [54]:
data.loc['Nadia']

id                               1
last_name                   Smylie
email         nsmylie0@tinyurl.com
gender                      Female
ip_address           14.132.133.60
Name: Nadia, dtype: object