In [2]:
import pandas as pd
import numpy as np

In [32]:
data = [
    {'name':'vishal',
    'age':21,
    'marks': 70,
    'mobileno':976097997},
    {'name':'shayam',
    'age':22,
    'marks': 75,
    'mobileno':976797997},
    {'name':'hritik',
    'age':25,
    'marks': 76,
    'mobileno':97667997},
    {'name':'Lalit',
    'age':24,
    'marks': 82,
    'mobileno':32547997},
]
df=pd.DataFrame(data)
df

     name  age  marks   mobileno
0  vishal   21     70  976097997
1  shayam   22     75  976797997
2  hritik   25     76   97667997
3   Lalit   24     82   32547997

In [33]:
df[['name','marks']]

     name  marks
0  vishal     70
1  shayam     75
2  hritik     76
3   Lalit     82

In [34]:
df.loc[:,['name','marks']]

     name  marks
0  vishal     70
1  shayam     75
2  hritik     76
3   Lalit     82

In [35]:
df.set_index('name',inplace=True)
df

        age  marks   mobileno
name
vishal   21     70  976097997
shayam   22     75  976797997
hritik   25     76   97667997
Lalit    24     82   32547997

In [36]:
df.loc[['vishal','Lalit']]

        age  marks   mobileno
name
vishal   21     70  976097997
Lalit    24     82   32547997