In [1]:
import pandas as pd
import numpy as np

In [9]:
df= pd.read_csv('MOCK_DATA.csv')

In [10]:
df

,RollNo,Name,Branch,Book_title,issuedate,returndate,fine
0,1,Martita,Chief Design Engineer,Straightheads (Closure),21 September 2025,30 December 2025,775
1,1,Martita,Chief Design Engineer,Data Structures and Algorithms,15 January 2026,20 February 2026,120
2,2,Frannie,Statistician II,"House I Live In, The",23 July 2025,08 March 2026,945
3,2,Frannie,Statistician II,Database Management Systems,05 April 2026,18 May 2026,35
4,3,Curt,Payment Adjustment Coordinator,"Last Samurai, The",03 September 2025,01 January 2026,260
5,3,Curt,Payment Adjustment Coordinator,Operating Systems,12 February 2026,28 March 2026,150
6,4,Hillier,Community Outreach Specialist,Tears of the Black Tiger (Fah talai jone),05 January 2026,01 February 2026,487
7,5,Leticia,Data Coordinator,Three of Hearts,12 September 2025,21 March 2026,435
8,5,Leticia,Data Coordinator,Computer Networks,01 April 2026,15 May 2026,90
9,6,Nananne,Professor,Varg Veum - Bitter Flowers (Varg Veum - Bitre ...,16 September 2025,21 January 2026,134
10,6,Nananne,Professor,Artificial Intelligence,18 February 2026,22 March 2026,0
11,7,Darrell,Chemical Engineer,Afflicted,29 January 2026,19 February 2026,216
12,8,Gar,Mechanical Systems Engineer,Tribes,08 February 2026,26 February 2026,541
13,9,Joanna,Web Developer I,"World of Suzie Wong, The",17 November 2025,22 December 2025,721
14,10,Delly,Staff Accountant III,Belle époque,01 May 2026,31 May 2026,901

In [31]:
result = df.groupby(['RollNo','Name']).size()
result

RollNo  Name
1       Martita    2
2       Frannie    2
3       Curt       2
4       Hillier    1
5       Leticia    2
6       Nananne    2
7       Darrell    1
8       Gar        1
9       Joanna     1
10      Delly      1
dtype: int64

In [33]:
result = df.groupby(['RollNo','Name'])['fine'].sum()
result

RollNo  Name
1       Martita    895
2       Frannie    980
3       Curt       410
4       Hillier    487
5       Leticia    525
6       Nananne    134
7       Darrell    216
8       Gar        541
9       Joanna     721
10      Delly      901
Name: fine, dtype: int64

In [43]:
result = df.groupby(['Book_title','RollNo'])['Name'].size()
result

Book_title                                               RollNo
Afflicted                                                7         1
Artificial Intelligence                                  6         1
Belle époque                                             10        1
Computer Networks                                        5         1
Data Structures and Algorithms                           1         1
Database Management Systems                              2         1
House I Live In, The                                     2         1
Last Samurai, The                                        3         1
Operating Systems                                        3         1
Straightheads (Closure)                                  1         1
Tears of the Black Tiger (Fah talai jone)                4         1
Three of Hearts                                          5         1
Tribes                                                   8         1
Varg Veum - Bitter Flowers (Varg Veum - Bitre Blomster)  6         1
World of Suzie Wong, The                                 9         1
Name: Name, dtype: int64

In [46]:
result = df.groupby(['RollNo','Name']).agg({'fine':['mean','max','min']})
result

                 fine
                 mean  max  min
RollNo Name
1      Martita  447.5  775  120
2      Frannie  490.0  945   35
3      Curt     205.0  260  150
4      Hillier  487.0  487  487
5      Leticia  262.5  435   90
6      Nananne   67.0  134    0
7      Darrell  216.0  216  216
8      Gar      541.0  541  541
9      Joanna   721.0  721  721
10     Delly    901.0  901  901

In [48]:
result = df.groupby('Branch').agg({'fine':'sum'})
result

                                fine
Branch
Chemical Engineer                216
Chief Design Engineer            895
Community Outreach Specialist    487
Data Coordinator                 525
Mechanical Systems Engineer      541
Payment Adjustment Coordinator   410
Professor                        134
Staff Accountant III             901
Statistician II                  980
Web Developer I                  721

In [40]:
result = df.groupby('issuedate').size()
result

issuedate
01 April 2026        1
01 May 2026          1
03 September 2025    1
05 April 2026        1
05 January 2026      1
08 February 2026     1
12 February 2026     1
12 September 2025    1
15 January 2026      1
16 September 2025    1
17 November 2025     1
18 February 2026     1
21 September 2025    1
23 July 2025         1
29 January 2026      1
dtype: int64