In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_Of_Birth ': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'age': [12, 12, 13, 13, 14, 12],
    'height': [173, 192, 186, 167, 151, 159],
    'weight': [35, 32, 33, 30, 31, 32],
    'address': ['street1', 'street2', 'street3', 'street1', 'street2', 'street4']})

In [6]:
df

,school_code,class,name,date_Of_Birth,age,height,weight,address
0,s001,V,Alberto Franco,15/05/2002,12,173,35,street1
1,s002,V,Gino Mcneill,17/05/2002,12,192,32,street2
2,s003,VI,Ryan Parkes,16/02/1999,13,186,33,street3
3,s001,VI,Eesha Hinton,25/09/1998,13,167,30,street1
4,s002,V,Gino Mcneill,11/05/2002,14,151,31,street2
5,s004,VI,David Parkes,15/09/1997,12,159,32,street4

## WAP to find out the size of school code

In [10]:
result = df.groupby('school_code').size()
result

school_code
s001    2
s002    2
s003    1
s004    1
dtype: int64

In [14]:
result = df.groupby('school_code')['age'].max()
result

school_code
s001    13
s002    14
s003    13
s004    12
Name: age, dtype: int64

In [18]:
result = df.groupby('school_code').agg({'age':['max']})
result

            age
            max
school_code
s001         13
s002         14
s003         13
s004         12

## Write a Pandas program to split the following dataframe by school code and get mean, min, and max value of age for each school

In [22]:
result = df.groupby('school_code').agg({'age':['max','min','mean']})

In [23]:
result

            age
            max min  mean
school_code
s001         13  12  12.5
s002         14  12  13.0
s003         13  13  13.0
s004         12  12  12.0

In [25]:
result = df.groupby(['school_code','class']).agg({'age':['max','min','mean']})
result

                  age
                  max min  mean
school_code class
s001        V      12  12  12.0
            VI     13  13  13.0
s002        V      14  12  13.0
s003        VI     13  13  13.0
s004        VI     12  12  12.0

In [28]:
result = df.groupby(['school_code','class']).agg({'age':['max','min','mean'],'height':['max','min','mean']})
result

                  age           height
                  max min  mean    max  min   mean
school_code class
s001        V      12  12  12.0    173  173  173.0
            VI     13  13  13.0    167  167  167.0
s002        V      14  12  13.0    192  151  171.5
s003        VI     13  13  13.0    186  186  186.0
s004        VI     12  12  12.0    159  159  159.0

## select age,height from df groupby school_code,class where age == max

## Write a Pandas program to split a dataset, group by one column and get mean, min, and max values by group. Using the following dataset find the mean, min, and max values of purchase amount (purch_amt) group by customer id (customer_id).

In [18]:
od = pd.DataFrame({
'ord_no':[70001,70009,70002,70004,70007,70005,70008,70010,70003,70012,70011,70013],
'purch_amt':[150.5,270.65,65.26,110.5,948.5,2400.6,5760,1983.43,2480.4,250.45, 75.29,3045.6],
'ord_date': ['2012-10-05','2012-09-10','2012-10-05','2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'customer_id':[3005,3001,3002,3009,3005,3007,3002,3004,3009,3008,3003,3002],
'salesman_id': [5002,5005,5001,5003,5002,5001,5001,5006,5003,5002,5007,5001]})

In [19]:
od

    ord_no  purch_amt    ord_date  customer_id  salesman_id
0    70001     150.50  2012-10-05         3005         5002
1    70009     270.65  2012-09-10         3001         5005
2    70002      65.26  2012-10-05         3002         5001
3    70004     110.50  2012-08-17         3009         5003
4    70007     948.50  2012-09-10         3005         5002
5    70005    2400.60  2012-07-27         3007         5001
6    70008    5760.00  2012-09-10         3002         5001
7    70010    1983.43  2012-10-10         3004         5006
8    70003    2480.40  2012-10-10         3009         5003
9    70012     250.45  2012-06-27         3008         5002
10   70011      75.29  2012-08-17         3003         5007
11   70013    3045.60  2012-04-25         3002         5001

In [20]:
result = od.groupby('customer_id').agg({'purch_amt':['max','min','mean']})
result

            purch_amt
                  max      min         mean
customer_id
3001           270.65   270.65   270.650000
3002          5760.00    65.26  2956.953333
3003            75.29    75.29    75.290000
3004          1983.43  1983.43  1983.430000
3005           948.50   150.50   549.500000
3007          2400.60  2400.60  2400.600000
3008           250.45   250.45   250.450000
3009          2480.40   110.50  1295.450000

## SQL select customer_id, avg('purch_amt'),max('purch_amt'),min('purch_amt') from customer groupby ('customer_id')

## Q. Write a Pandas program to split the following dataframe into groups based on customer id and create a list of order date for each group

In [25]:
# order_dates = od.groupby('customer_id')['ord_date'].apply(list)
order_dates = od.groupby('customer_id').agg({'ord_date':'max'}).apply(list)
order_dates

               ord_date
customer_id
3001         2012-09-10
3002         2012-10-05
3003         2012-08-17
3004         2012-10-10
3005         2012-10-05
3007         2012-07-27
3008         2012-06-27
3009         2012-10-10

## Write a Pandas program to split the following dataframe into groups, group by month and year based on order date and find the total purchase amount year wise, month wise

In [ ]:
od["ord_date"] = pd.to_datetime(df["ord_date"])
ans = od.groupby([df["ord_date"].dt.year, od["ord_date"].dt.month]).agg({"purch_amt": "sum"})

## WAP to find out the department wise salary of only full time employees

In [9]:
df = pd.DataFrame({ 'Department': ['HR', 'IT', 'IT', 'HR', 'IT', 'HR'], 'Status': ['Full-Time', 'Full-Time', 'Part-Time', 'Part-Time', 'Full-Time', 'Full-Time'], 'Salary': [50000, 80000, 40000, 30000, 90000, 55000] })
df

  Department     Status  Salary
0         HR  Full-Time   50000
1         IT  Full-Time   80000
2         IT  Part-Time   40000
3         HR  Part-Time   30000
4         IT  Full-Time   90000
5         HR  Full-Time   55000

In [16]:
# result = df.query("Status== 'Full-Time'").groupby('Department')['Salary'].sum()
result = df.query("Status== 'Full-Time'").groupby('Department').agg({'Salary':'sum'})

In [17]:
result

            Salary
Department
HR          105000
IT          170000